language: go

go:
  - 1.3
  - 1.4

git:
  depth: 1

install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/lint/golint
  - go get github.com/tools/godep
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - golint .
  - godep go test -race ./...
  - godep go test -cover ./...
